### ISSUE TITLE
FR: Make reservation editable / Insert new reservations

### ISSUE THREAD

**Issue by jscholtysik** [dennis-sagasser/contao-table-reservation#10]
Please provide a possibility that the restaurant owner can edit existing entries from customers and is also able to add new entries via Contao backend, because a customer is already in the restaurant and want to book a reservation for the news days (Frontend-Editing?). So the restaurant owner can immediately insert the new reservation.

**Comment by jscholtysik** [comment]
Unfortunately the mandatory fields in the frontend are not mandatory in the backend, so please make also the fields "first name" and "email" mandatory in the backend.
Please also add the salutation field to the backend mask as this is missing. The backend fields should be the same as the frontend fields.

**Comment by dennis-sagasser** [comment]
Why do you think these fields should be mandatory? I think about the situation where somebody calls the restaurant and the waiter only wants to fill in quickly the name and the number of persons as usual. Do you think that firstname and email is important for oral reservations?

**Comment by jscholtysik** [comment]
What does the restaurant owner or the waiter do, when he can't hold the date? How shall they  contact the client and tell him or her that the date was cancelled? One of the fields email or telefone must be mandatory to contact the client imho...

**Comment by dennis-sagasser** [comment]
Now I added  salutation to the backend fields and made the phone field mandatory for manual reservation inputs. Do you agree with that?

**Comment by jscholtysik** [comment]
Agreed. Thank you!
