### ISSUE TITLE
FR: Change time format: Delete seconds

### ISSUE THREAD

**Issue by jscholtysik** [dennis-sagasser/contao-table-reservation#11]
Seconds do not make sense in a reservation, so a shorter time format seems to be a better choice:

Example:

Date and Time: 13.07.2017 19:00
or
Date and Timeslot: 13.07.2017 19:00 - 20:30

**Comment by dennis-sagasser** [comment]
Date and time format can either be set in the global settings or in the root page settings of the site structure.

**Comment by jscholtysik** [comment]
That does only makes sense, when I want to have a date and time format that should be valid for the whole website. When I want to have different formats for example for a news Page and the reservation, it makes no sense...

**Comment by dennis-sagasser** [comment]
Good point. Thx.

**Comment by jscholtysik** [comment]
Please also delete the seconds from the table in the frontend, when a reservation is possible:

![bildschirmfoto 2017-03-15 um 18 16 21](https://cloud.githubusercontent.com/assets/1425566/23961537/86a3c05e-09ab-11e7-8e49-b15b3e0a7a9f.png)

And also in the reservations list in the backend:

![bildschirmfoto 2017-03-15 um 19 20 39](https://cloud.githubusercontent.com/assets/1425566/23964379/93f807b6-09b4-11e7-9b81-980eea59bb06.png)
