### ISSUE TITLE
Issue: Two different bubble helps for one field...

### ISSUE THREAD

**Issue by jscholtysik** [dennis-sagasser/contao-table-reservation#12]
Every mandatory field has now two bubble helps:

When I hover for example over the date/time field, there is a small bubble help (from Contao):

![image1](https://cloud.githubusercontent.com/assets/1425566/23962049/247eb40e-09ad-11e7-9a32-6a3cb003afa0.png)

When i press the button "Verfügbarkeit prüfen" and the field is empty, I get this bigger bubble help (from Bootstrap?):

![image2](https://cloud.githubusercontent.com/assets/1425566/23962100/4f8e9c22-09ad-11e7-869b-9aac54a0edaa.png)

is is possible to get only the error messages from Contao? This problem is related to all mandatory input fields...

**Comment by dennis-sagasser** [comment]
Yes. That is no error. It is HTML5 error validation and comes from the browser. See https://contao.ninja/html5-validation.html.

**Comment by jscholtysik** [comment]
Ich möchte ja nicht die HTML5 Fehlerüberprüfung komplett ausschalten, deshalb macht für mich der Parameter novalidate="novalidate" keinen Sinn. 
Ich möchte erreichen, dass eine der beiden Meldungen überhaupt nicht erscheint, entweder 
- die kleine Meldung, die von Contao beim Hovern erzeugt wird, keine Fehlermeldung ist und vor dem Drücken von "Verbindlich reservieren" als Hinweis beim Feld angezeigt wird oder 
- die große Meldung, die anscheinend von Bootstrap beim Validieren des Formulars erzeugt wird und dann aber eine reine Fehlermeldung ist, dass das Feld ausgefüllt werden muss.

Das sind zwei unterschiedliche Meldungen (Hinweis - Fehler)...

Wenn ich das mit novalidate="novalidate" ausschalte, habe ich ja auch keine Tooltipps mehr bei den Feldern.

**Comment by dennis-sagasser** [comment]
The two bubbles seem to be a part of the html5 validation of the browser. You can check that by deactivating JavaScript. Certainly every browser handles that in its own way. My proposal is to activate the html5 validation again to be more user friendly and save bandwidth.

**Comment by jscholtysik** [comment]
Dann bitte wieder die Validierung einschalten. Danke!

**Comment by jscholtysik** [comment]
Im Forum gibt es gerade auch eine Diskussion dazu mit einer möglichen Lösung:

https://community.contao.org/de/showthread.php?4002-Formular-Error-Message-positionieren&p=436376#post436376
