### ISSUE TITLE
FR: Separate number of persons/seats and category in frontend and backend

### ISSUE THREAD

**Issue by jscholtysik** [dennis-sagasser/contao-table-reservation#13]
When a reservation is possible, the following table will be shown in the frontend:

![bildschirmfoto 2017-03-15 um 18 16 21](https://cloud.githubusercontent.com/assets/1425566/23962293/e80d7f72-09ad-11e7-8157-dbbdc9a4111a.png)

For a better overview it would be better, if the table would show three columns:
Datum und Uhrzeit | Sitzplätze | Kategorie

Also in the backend it would be better to separate the two fields for a faster input and change the list wizard to single fields, for example two select fields:
Field 1 contains the all entries until the maximum number of possible seats from "Tischkategorien")
Field 2 contains all the possible categories from "Tischkategorien" 

This is the actual view:

![bildschirmfoto 2017-03-15 um 18 39 07](https://cloud.githubusercontent.com/assets/1425566/23962951/0a3b98c0-09b0-11e7-947c-609562cb86be.png)

So the waiter does not have to know what categories exist or has first to look for the existing categories and can immediately see all available categories and choose the one he needs from a select field.

And also in the reservations list:

![bildschirmfoto 2017-03-15 um 19 20 39](https://cloud.githubusercontent.com/assets/1425566/23964422/b76836b2-09b4-11e7-8aec-836d65707cd3.png)

**Comment by jscholtysik** [comment]
Only a small request for a name correction in "Reservierungsliste":

The question mark at "Sitzplätze(?)" still shows 
"Bitte wählen Sie die gewünschte Personenanzahl und Kategorie aus." -->  "Bitte wählen Sie die gewünschte Personenanzahl aus". 

And I would also name the headline and the description exact the same way: 
Either "Sitzplätze(?) --> Bitte wählen Sie die gewünschte Sitzplatzanzahl aus" or
Personen(?) --> Bitte wählen Sie die gewünschte Personenanzahl aus." 

Because all other information is already named "Personen", i would prefer the second possibility. and change "Sitzplätze(?)" to "Personen(?).

![bildschirmfoto 2017-03-28 um 18 56 01](https://cloud.githubusercontent.com/assets/1425566/24417611/5ace0884-13e9-11e7-8ac8-747411aa2db2.png)

**Comment by jscholtysik** [comment]
Thank you! So the wording in the frontend

![bildschirmfoto 2017-03-29 um 09 33 51](https://cloud.githubusercontent.com/assets/1425566/24443422/dc07b14c-1462-11e7-9b28-fe266fa7163f.png)

and in the settings in "HTML-Inhalt" should also be changed to Personen:

![bildschirmfoto 2017-03-29 um 09 34 30](https://cloud.githubusercontent.com/assets/1425566/24443451/ffc2af74-1462-11e7-94a5-5aaf6752f126.png)

**Comment by jscholtysik** [comment]
These latest changes of 06f5cc2 are not shown in my demo page in the settings at "HTML-Inhalt". Here is still shown "Sitzplätze: {{reservation::seats}}"... it seems that the file "languages/de/tl_table_reservation_settings.php" is not used. 

What can I do to get the actual german translation?

Furthermore no content is shown in "Text-Inhalt". That seems to be the same problem with "languages/de/tl_table_reservation_settings.php".

![bildschirmfoto 2017-04-05 um 11 47 45](https://cloud.githubusercontent.com/assets/1425566/24699865/c05c2cf0-19f5-11e7-879d-4eee6146b6cc.png)


And last but not least the wording in german and english shouls be the same:
German: Sitzplätze --> Personen
English: Seats --> Persons

**Comment by dennis-sagasser** [comment]
The content is a default value and is inserted when you install the extension.
I chose html content as default. So there is no need to fill the plain text textarea.

**Comment by jscholtysik** [comment]
Ok checked. Thank you for clarification. I thought, the settings will always be reset when I renew the files in the system/modules/table_reservation/ folder, but once installed, the values are copied to the table tl_table_reservation_settings and are no more touched by the install settings, only from the backend changes.
