### ISSUE TITLE
FR: Split inserttag {{reservation::seats}} into two inserttags

### ISSUE THREAD

**Issue by jscholtysik** [dennis-sagasser/contao-table-reservation#15]
Split inserttag {{reservation::seats}} into two inserttags:

Inserttag 1: {{reservation::seats}} 
Inserttag 2: {{reservation::category}}

Followup to https://github.com/dennis-sagasser/contao-table-reservation/issues/13

**Comment by dennis-sagasser** [comment]
Splitting inserttag won't be possible because there is the possibility to reserve seats for more than one category. So one inserttag is needed for the string that contains the number of persons and category name.
