### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by chriza** [dennis-sagasser/contao-table-reservation#16]
Hallo,
habe table-reservation installiert. Die Icons werden wegen eines 403 Errors nicht angezeigt, dadurch ist die Funktionalität nicht gegeben.
![26-03-_2017_14-29-22](https://cloud.githubusercontent.com/assets/1572887/24331290/69fe18ee-1231-11e7-9b37-ad8836214ad5.jpg)

**Comment by dennis-sagasser** [comment]
Hi,

ist bei dir die .htaccess vorhanden im assets-Ordner? Läuft bei dir ein Apache Webserver? Haben alle Modulordner die richtigen Berechtigungen?

**Comment by chriza** [comment]
Hi,
jungfräuliche Installation bei ALL-INKL. Die ROOM-Extension läuft problemlos.

**Comment by dennis-sagasser** [comment]
Hallo,
ich bin neugierig. Was war es?

**Comment by chriza** [comment]
Hi,
die Extension reservation läuft. Bei der Extension table-reservation kommt es zu dem 403 Error.

**Comment by jscholtysik** [comment]
Hi Chriza,

ich bin auch bei All-Inkl, dort läuft table-reservation ohne Probleme...

**Comment by chriza** [comment]
Ich habe gerade wieder eine neue Installation erstellt. Der gleiche 403 Fehler.

**Comment by jscholtysik** [comment]
Was sagt der Contao Check? Alles ok?

**Comment by chriza** [comment]
Ist alles ok!
Könntest Du die Extension einmal in einer neuen Installation installieren?

**Comment by jscholtysik** [comment]
Ich habe gerade noch einmal eine frische Installation bei All-Inkl aufgesetzt, Table Reservation unter system/modules installiert und dann die Datenbank aktualisiert. Alles ok und die Symbole im Backend sind auch vorhanden. 

Wichtig ist, dass der Ordner unter system/modules den Namen "table_reservation" hat. 

![bildschirmfoto 2017-03-27 um 12 20 53](https://cloud.githubusercontent.com/assets/1425566/24351908/ddb78368-12e7-11e7-8b38-0f82c73acf90.png)

**Comment by chriza** [comment]
Und da haben wir den Fehler: Beim Installieren aus dem Repository wird in system/modules der Ordner table-reservation statt table_reservation erzeugt.

**Comment by jscholtysik** [comment]
Der richtige Pfad ist in der config.php unter /system/modules/table_reservation/config/ zu sehen, die Pfade für die Symbole stehen dort drin. Ich hatte den Fehler nicht, da ich die Dateien manuell in das Verzeichnis kopiert hatte.

**Comment by dennis-sagasser** [comment]
Habe die aktuelle master-Version ins ER von Contao gestellt. Damit sollte es laufen...
