### ISSUE TITLE
Issue: Small typo at "Öffnungszeiten" in the backend

### ISSUE THREAD

**Issue by jscholtysik** [dennis-sagasser/contao-table-reservation#17]
In the tooltip there ist a small typo at "Öffnungszeiten":

"Geben Sie die Öffungszeiten..." --> Geben Sie die Öffnungszeiten..." (with an additional N)

**Comment by dennis-sagasser** [comment]
#9

**Comment by dennis-sagasser** [comment]
Fixed in #9 - FR: Option in settings to select between a point of time o…
