### ISSUE TITLE
FR: Possibility to sort the reservation list

### ISSUE THREAD

**Issue by jscholtysik** [dennis-sagasser/contao-table-reservation#18]
Please make it possible to automatically or manually sort the entries in the reservation list according to the day of reservation from the close to the future dates in ascending order. In my screenshot I have 18.05.2017 before  15.05.2017, normally it should first show the dates that are closer to the actual date.

![bildschirmfoto 2017-03-28 um 19 12 44](https://cloud.githubusercontent.com/assets/1425566/24418060/ffebf35c-13ea-11e7-9038-c9a100710afc.png)

**Comment by dennis-sagasser** [comment]
You can sort the list by the options from the listing dropdown above. Is that what you are looking for?

**Comment by jscholtysik** [comment]
No, in the filter select menues it is only possible to select a specific and single date or name to show. It is not possible to select for example a certain period... 
Is it possible to sort the entries already at fetching from the database and then display the entries in the right order (chronologically) additionally to the filter functions above? What if the waiter wants to see reservations for the next 7 days? Or the next month? Actually it is not possible, because the entries are in the wrong order, see No. 4, 5, 8 and 9.
I think, a sorted list would also be enough.

**Comment by dennis-sagasser** [comment]
If I sort by date and time I get this result:
![auswahl_001](https://cloud.githubusercontent.com/assets/8061288/24452434/829266fe-1483-11e7-99ec-a523f177b547.png)
This is a sorted list by date, isn't it? 
By default I set the reservation list sorting to ID to have a timeline overview.

**Comment by jscholtysik** [comment]
That is a sorted list by date, yes, but in the wrong order (must start with the oldest date, mustn't it?).

Date and Time sort in the wrong order (newest --> oldest), Nachname in the right order (Nachname and Datum are correct: First sort for Nachname, then sort for Date... so the sorting must be reversed at Date and Time.

Wrong:

![bildschirmfoto 2017-03-29 um 15 16 52](https://cloud.githubusercontent.com/assets/1425566/24456271/cfc5f648-1492-11e7-9ac4-790119608c87.png)

Right:

![bildschirmfoto 2017-03-29 um 15 17 46](https://cloud.githubusercontent.com/assets/1425566/24456302/e6fe2b64-1492-11e7-9bc1-1b57cbefd344.png)

**Comment by dennis-sagasser** [comment]
We are getting closer :P. Why do you want to show the oldest first? Why would anyone first care about (eventual) expired reservations? Compared with a news blog it would make no sense, wouldn't it?

**Comment by jscholtysik** [comment]
Combined with https://github.com/dennis-sagasser/contao-table-reservation/issues/19 there would be no expired reservations anymore in the list, only actual and coming reservations... ;-) Why would it make sense to show first reservations that lie in the far future than the reservations that are close to the actual date?

Example: The waiter wants to look for the reservations of tomorrow, so why should we show him the reservations first that are in two weeks? So he has actually to scroll down to the reservations of tomorrow. In my mind the sort algorithm must be reverted to first get the reservations of tomorrow...

**Comment by jscholtysik** [comment]
What about the DCA sorting flags 11 and 12 after choosing Date and Time?

**Comment by dennis-sagasser** [comment]
Ok. Together with #19 that sounds plausible.
