### ISSUE TITLE
FR: Don't show expired reservations

### ISSUE THREAD

**Issue by jscholtysik** [dennis-sagasser/contao-table-reservation#19]
Is it possible to offer a toggler in the settings or directly in the reservation list where the waiter can choose whether he wants to see the expired reservations or not? Otherwise the list can be extremely long...

**Comment by dennis-sagasser** [comment]
Listing only future reservations by default is no problem. Customized filtering requires some more effort.

**Comment by dennis-sagasser** [comment]
Fixed in #18.

**Comment by jscholtysik** [comment]
Thank you. Despite this change the waiter should also have the possibility to call expired reservations for resurvey. So my idea was a toggler button where the waiter can decide himself if he wants to see the expired and the future reservations or only the future reservations in the overview...

**Comment by jscholtysik** [comment]
Unfortunately the new and third filter select box is a little bit to wide with 200px, that means that it is now partly shown out of the Contao backend on the right side and the distance between the second and the new filter select box is also a little bit to big compared to the first and second filter select boxes.
