### ISSUE TITLE
FR: Replace dependancy with contao-calendarfield

### ISSUE THREAD

**Issue by jscholtysik** [dennis-sagasser/contao-table-reservation#2]
The composer says that terminal42/contao-calendarfield is abandoned and should be replaced with hofff/contao-calendarfield. Therefore please replace the dependancy so that hofff/contao-calendarfield is the new dependancy.

**Comment by jscholtysik** [comment]
This is a screenshot from the Contao 3.5 packet management:

![bildschirmfoto 2017-03-27 um 11 46 00](https://cloud.githubusercontent.com/assets/1425566/24350588/0fe0f0cc-12e3-11e7-8fac-f8d8903c577d.png)

**Comment by jscholtysik** [comment]
Gibt es denn schon eine Tendenz, ob die Terminal42-Calendarfield-Extension durch die Hofff-Calendarfield-Extension ersetzt wird / werden kann? Wäre toll, wenn man die Abandoned-Meldung wegbringen könnte...

**Comment by jscholtysik** [comment]
The dependency for hofff/contao-calendarfield in the README.MD is still missing.

**Comment by dennis-sagasser** [comment]
Yes, because it is not used. The hofff extension does not support a time picker. Flatpickr is integrated now.

**Comment by jscholtysik** [comment]
Ah, ok, thanks for clarification.

**Comment by jscholtysik** [comment]
But I have found another bug, that comes perhaps from the new code in templates/mod_table_reservation_form.html5, lines 101 - 119:

![bildschirmfoto 2017-05-08 um 12 33 04](https://cloud.githubusercontent.com/assets/1425566/25800683/99842ec0-33ea-11e7-940f-ad60957cd818.png)

There is an unused "d.m.Y" under the table reservation module.

**Comment by jscholtysik** [comment]
And the "Jetzt reservieren" link has lost its formatting as a button and is now shown as a normal link...

**Comment by dennis-sagasser** [comment]
Oh. I see. Thanks!
