### ISSUE TITLE
Issue: The reservation list doesn't show any entries anymore...

### ISSUE THREAD

**Issue by jscholtysik** [dennis-sagasser/contao-table-reservation#20]
After the last changes the reservation list is now empty. Also a manual entry in the reservation list is no more shown...

**Comment by dennis-sagasser** [comment]
Did you set any filter options? Are there error messages? Is the database table empty?

**Comment by jscholtysik** [comment]
Asche auf mein Haupt: Ich hatte vergessen, die Filter wieder zurück zu setzen... :-(

Sorry.

**Comment by dennis-sagasser** [comment]
Hatt ich auch schon mal😉
