### ISSUE TITLE
Issue:  Mandatory fields

### ISSUE THREAD

**Issue by jscholtysik** [dennis-sagasser/contao-table-reservation#21]
Concerning the german data privacy law all fields in contact forms don't have to be mandatory except the email field, so please change the fields firstname and lastname in backend and frontend not to be mandatory.

**Comment by jscholtysik** [comment]
Sorry, the salutation in the frontend is also still mandatory field und must be corrected... :-(

**Comment by dennis-sagasser** [comment]
Can you specify a person by his/her gender? I think there is no need to remove the mandatory field is it?

**Comment by jscholtysik** [comment]
IMHO is does not make sense to leave the salutation field alone mandatory when all other address fields are not. For consistency it should be changed, because in my mind it is also part of the address...
