### ISSUE TITLE
Fehler beim Aufruf der Einstellungen

### ISSUE THREAD

**Issue by jscholtysik** [dennis-sagasser/contao-table-reservation#27]
Wenn man im Backend in die Einstellungen der Tischreservierung gehen möchte, wird die /contao/confirm.php aufgerufen und folgender Fehler erscheint:

![fehler_modul_einstellungen](https://cloud.githubusercontent.com/assets/1425566/25823200/9c6d962a-343b-11e7-936c-0633a09fd7a7.jpg)

Ist auf der Kundenseite und in meiner Demo-Installation dasselbe Problem.

**Comment by ghost** [comment]
Habe die aktuelle Version gerade über den Contao-Erweiterungskatalog installiert und erhalte den gleichen Fehler. Ist der Fix im aktuellen Release gar nicht enthalten und muss die Korrektur manuell erfolgen? Sorry, das ist mir irgendwie nicht ganz klar.

Gibt es irgendwo eigentlich sowas wie ein grobe Übersicht, wo was einzustellen ist, damit man die Erweiterung zum Laufen bekommt? Habe zwar Termine, Wiederholungen, Zeitfenster etc. gepflegt, aber Buchen kann ich irgendwie nicht.

**Comment by dennis-sagasser** [comment]
Beim Erstellen des Releases habe ich wahrscheinlich eine nicht aktuelle Version genommen. Sorry. Nun sollten die Einstellungen wieder erreichbar sein. 

Warum kannst du nicht buchen? Gibt es eine Fehlermeldung?
