### ISSUE TITLE
Von-Bis bei aktiviertem Zeitfenster

### ISSUE THREAD

**Issue by ghost** [dennis-sagasser/contao-table-reservation#29]
Ist in den Zeitfenster-Einstellungen "Zeitfenster veröffentlichen" aktiviert, wird bei Buchung eines Termins nur die Bis-Zeit angezeigt. Richtiger wäre die Von-Zeit oder besser Von-Bis inklusive Datumsangabe:

![zeitfenster aktiviert](https://user-images.githubusercontent.com/29429097/27166774-6883bb44-519d-11e7-8ced-6db588d41beb.JPG)

Anzeige bei Buchung:
![anmeldung](https://user-images.githubusercontent.com/29429097/27166883-f0169446-519d-11e7-9ee1-72b00e518061.JPG)

Gleiches trifft auf die Bestätigungs-Email zu:

![email](https://user-images.githubusercontent.com/29429097/27166891-faf8971a-519d-11e7-9566-e7aab6a462c3.JPG)

**Comment by dennis-sagasser** [comment]
Ja. Genau. So sollte das auch sein. Ist das nach dem Update immer noch so?

**Comment by jscholtysik** [comment]
Ich habe mir gerade noch mal die aktuelle ZIP-Datei heruntergeladen.
Funktioniert bei mir ohne Probleme:

Die Buchung:

![tischreservierung](https://user-images.githubusercontent.com/1425566/27289680-16bebe1e-550b-11e7-80f6-ed35b2ad4232.jpg)

Die E-Mail dazu:

![tischreservierung_e-mail](https://user-images.githubusercontent.com/1425566/27289915-e02c7f70-550b-11e7-8480-0f418a6a80b7.jpg)

**Comment by ghost** [comment]
Hab's gerade nochmal ausprobiert. Zeigt bei mir nur die Bis-Zeit an, ohne Datum. Version 1.1.4 Build 2

Ist auch nicht ausgeblended oder versteckt oder so - fehlt einfach:

 

<div class="info">
        Für den ausgewählten Zeitraum ist eine Reservierung möglich:        <br><br>
        <table id="overviewTable">
            <thead>
            <tr>
                <td><strong>Datum und Zeit</strong></td>
                <td><strong>Personen</strong></td>
                <td><strong>Tischkategorie</strong></td>
            </tr>
            </thead>
            <tr>
                <td rowspan="1">
                     - 10:30&nbsp;
                </td>
                                <td>1</td>
                <td>Massage</td>
            </tr>
                    </table>
    </div>

**Comment by dennis-sagasser** [comment]
Funktioniert die Buchung ohne Zeitfenster? Was sagt die Buchungsliste im Backend?

**Comment by ghost** [comment]
Die Buchung für den entsprechenden Zeitraum funktioniert dennoch super und auch im Backend wird der Termin mit dem richtigen Startzeitpunkt angezeigt. Scheint lediglich ein Anzeigeproblem im Frontend zu sein.

**Comment by dennis-sagasser** [comment]
Gibt es einen Live-Link? Dann könnte ich schauen, ob nicht per CSS o.ä. etwas ausgeblendet wird.

**Comment by ghost** [comment]
Ist alles noch in der Test- und Entwicklungsphase, läuft daher ausschließlich hinter der Firewall im Intranet. Vielleicht hilft das aber:

![von-bis](https://user-images.githubusercontent.com/29429097/28102731-76a1a6ac-66d1-11e7-870a-82d10aa5b179.JPG)

Von Contao / Table-reservation ausgelieferter Quelltext:

<hr>
    <div class="mod_table_reservation block" id="massage"    >

            <h1>Anmeldung zur Massage</h1>



    <div class="info">
        Für den ausgewählten Zeitraum ist eine Reservierung möglich:        <br><br>
        <table id="overviewTable">
            <thead>
            <tr>
                <td><strong>Datum und Zeit</strong></td>
                <td><strong>Personen</strong></td>
                <td><strong>Tischkategorie</strong></td>
            </tr>
            </thead>
            <tr>
                <td rowspan="1">
                     - 13:30&nbsp;
                </td>
                                <td>1</td>
                <td>Massage</td>
            </tr>
                    </table>
    </div>


<form action="" id="availability" method="post"
      enctype="application/x-www-form-urlencoded">
    <div class="formbody">
                    <input type="hidden" name="FORM_SUBMIT" value="form_availability_submit"/>
            <input type="hidden" name="REQUEST_TOKEN" value="67df504639a81f60493fcba7a706c853"/>
                <label for="ctrl_arrival"><span class="invisible">Pflichtfeld </span>Datum<span class="mandatory">*</span></label>        <input type="text" name="arrival" id="ctrl_arrival" class="text" value="19.07.2017" required><br>

        <label for="ctrl_timeslots"><span class="invisible">Pflichtfeld </span>Zeitfenster<span class="mandatory">*</span></label>        <select name="timeslots" id="ctrl_timeslots" class="" required><option value="">-</option><option value="09:30 - 10:00 - Massage_0930">09:30 - 10:00</option><option value="10:00 - 10:30 - Massage_1000">10:00 - 10:30</option><option value="10:30 - 11:00 - Massage_1030">10:30 - 11:00</option><option value="11:00 - 11:30 - Massage_1100">11:00 - 11:30</option><option value="11:30 - 12:00 - Massage_1130">11:30 - 12:00</option><option value="12:30 - 13:00 - Massage_1230">12:30 - 13:00</option><option value="13:00 - 13:30 - Massage_1300" selected>13:00 - 13:30</option><option value="13:30 - 14:00 - Massage_1330">13:30 - 14:00</option><option value="14:00 - 14:30 - Massage_1400">14:00 - 14:30</option><option value="14:30 - 15:00 - Massage_1430">14:30 - 15:00</option></select><br>

        <fieldset id="ctrl_tableCategory" class="checkbox_container"><legend><span class="invisible">Pflichtfeld </span>Tischkategorie wählen<span class="mandatory">*</span></legend><input type="hidden" name="tableCategory" value=""><span><input type="checkbox" name="tableCategory" id="opt_tableCategory_0" class="checkbox" value="1" checked required> <label id="lbl_tableCategory_0" for="opt_tableCategory_0">Massage</label></span> </fieldset><br>

        
                                            <label for="ctrl_1">Personen Massage</label>                <select name="1" id="ctrl_1" class=""><option value="0">0</option><option value="1" selected>1</option></select><br>
            <br>

            <input type="submit" id="ctrl_submit" class="submit btn btn-default" value="Verfügbarkeit prüfen">
                            <a class="btn btn-success" href="index.php/massage/FORM_PAGE/page2.html">
                    Jetzt reservieren »                </a>
            
            </div>
</form>


</div>
    <script type="text/javascript">
    // <![CDATA[
    flatpickr("#ctrl_arrival", {
        "minDate": "today",
        "locale": "de",
        "minuteIncrement": 15,
        "time_24hr": true,
        "weekNumbers": true,
        "enableTime": "false",
        "dateFormat": "d.m.Y",
    });
    // ]]>
</script>


<hr>

**Comment by dennis-sagasser** [comment]
Leider kann ich nicht viel erkennen. Ich kann mir vorstellen, dass etwas über CSS oder JS rausgefiltert wird, wenn ansonsten alles funktioniert. Werden zusätzliche Scripte / CSS-Dateien eingebunden?

**Comment by ghost** [comment]
Fällt mir schwer zu glauben. CSS hab ich selbst gemacht - da wird nichts gefiltert oder ausgeblendet. JavaScript - Hmm, weiss ich nicht. Könnte maximal durch eine andere Erweiterung passieren.

Kann ich Dir vielleicht aus dem Installationsverzeichnis von Table-Reservation irgendeine Datei zur Verfügung, die den Code generiert. Vielleicht ist ja irgendetwas nicht sauber aktualisiert worden beim letzten Update?

**Comment by dennis-sagasser** [comment]
Wie hast du das Ganze denn installiert? Über das Extension Repository? Du kannst auf jeden Fall hier auf GitHub die Moduldatei anschauen und sie ggf. ersetzen mit deiner Version.

**Comment by ghost** [comment]
Ja, ich hab das über das Extension Repository installiert. Geht einfach per Mausklick ohne viel Schnickschnack drumherum. Der Tip mit den Moduldateien hier auf GitHub ist gut, aber wo genau soll ich denn hinschauen? Die gefühlten 50 Dateien einzeln zu vergleichen erscheint mir etwas uneffektiv. Zumindest das Template sieht identisch aus:

**Mein Template:**
```
<tr>
                <td rowspan="<?= count($this->arrSeats); ?>">
                    <?= $this->arrSeats ? $this->objSession->get('arrival') : ''; ?>&nbsp;
                </td>
                <?php foreach ($this->arrSeats as $row): ?>
                <td><?= $row['count']; ?></td>
                <td><?= $row['categoryName']; ?></td>
            </tr>
```

**GitHub-Version:**
```
<tr>
                <td rowspan="<?= count($this->arrSeats); ?>">
                    <?= $this->arrSeats ? $this->objSession->get('arrival') : ''; ?>&nbsp;
                </td>
                <?php foreach ($this->arrSeats as $row): ?>
                <td><?= $row['count']; ?></td>
                <td><?= $row['categoryName']; ?></td>
</tr>
```

**Meine Ausgabe:**
```
Datum und Zeit | Personen | Kategorie
-- | -- | --
- 10:00 | 1 | Massage
```

**Quelltext dazu:**
```
<tr>
                <td rowspan="1">
                     - 10:00&nbsp;
                </td>
                                <td>1</td>
                <td>Massage</td>
            </tr>
```

Ich finde das schon sehr verwunderlich, wo das Minus vor 10:00 Uhr herkommt. Das konnte ich bisher nirgends aufspüren. Hilf mir doch mal bitte.

**Comment by dennis-sagasser** [comment]
Habe alle Templates und die Moduldatei verglichen und konnte keine Abweichungen feststellen bei der Version für das ER. Vor dem Minus sollte die von-Zeit stehen.

**Comment by ghost** [comment]
Sorry, wenn's jetzt vielleicht langsam lästig wird, aber es funktioniert nicht so, wie es soll. Aus meiner Usersicht hab' ich leider keinerlei Anhaltspunkt, woran es liegen könnte. 

Habe versucht, es nochmal komplett aufzubereiten. Alle Beispiele und Screenshots anhand einer Buchung für den **_16.08.2017 09:30 - 10:00 Uhr:_**

**1 - Einstellungen Zeitfenster:**
![1-einstellungen-zeitfenster](https://user-images.githubusercontent.com/29429097/29013922-78e2d8e4-7b46-11e7-8406-883174b5f73a.JPG)
Name ist identisch der jeweiligen Startzeit

**2 - Tischbelegung:**
![2-einstellungen-tischbelegung](https://user-images.githubusercontent.com/29429097/29013923-78e5a042-7b46-11e7-98bc-f7a1ba5f8cfb.jpg)
In jedem Timeslot am 16.08. ist jeweils 1 Platz frei.

**3 - Jetzt erfolgt der Versuch der Buchung**
![3-buchung](https://user-images.githubusercontent.com/29429097/29013925-78e88fdc-7b46-11e7-89af-926cc1801b22.JPG)
Buchungsversuch für den 16.08. 09:30 - 10:00 Uhr. Im Auswahlfeld "Zeitfenster" wird alles korrekt dargestellt, aber in der "overviewTable" eben nicht.

**4 - Template "mod_table_reservation_form.html5"**
![4-template](https://user-images.githubusercontent.com/29429097/29013921-78e1fb04-7b46-11e7-9891-bc16d46812f2.JPG)
Damit man die ausgegebenen Felder besser unterscheiden kann, hab ich das Template etwas verunstaltet. Wie man erkennt, kommt sowohl "10:00", als auch das Minuszeichen davor aus dem Feld "arrival" und departure scheint leer zu sein. Richtig wäre für Arrival aber 09:30 Uhr!

**5 - Buchungsdialog**
![5-buchung](https://user-images.githubusercontent.com/29429097/29013926-78e892a2-7b46-11e7-88b0-ba7c078b2b64.JPG)
Auch hier die gleiche falsche Anzeige.

**6 - Inhalt der Datenbanktabelle**
![6-db-inhalt](https://user-images.githubusercontent.com/29429097/29013924-78e80eea-7b46-11e7-8cac-1f2a2d4f4503.JPG)
Es drängt sich die Vermutung auf, dass die Daten in der Datenbank falsch sind. - scheint aber nicht so zu sein. Arrival und Departure sind beide gefüllt.

**7 - Email-Parameter:**
![7-einstellungen email](https://user-images.githubusercontent.com/29429097/29013927-78f7bbc4-7b46-11e7-8d94-b0b5985d9ea3.JPG)

**8 - verschickte Email**
![8-verschickte email](https://user-images.githubusercontent.com/29429097/29013928-78fa7256-7b46-11e7-8f28-22e2ac6bb4a7.JPG)
Auch die generierte Email enthält den gleichen Fehler


Arrival enthält scheinbar bei der Ausgabe über Tablereservation nirgends ein Datum und als Zeitstempel nur das Endedatum der Reservierung. 


**9 - Buchungsüberblick Contao-Modul**
![9-buchungsuberblick](https://user-images.githubusercontent.com/29429097/29013929-78fb7b92-7b46-11e7-90ec-24c86695467a.JPG)
Zur Ansicht der aktuellen Buchungen habe ich nach dem Reservierungsformular noch ein Modul vom Typ "Auflistung" eingefügt, dass mir den Inhalt der Tabelle tl_table_list ausgibt. Hier ist alles korrekt und sieht so aus, wie es sein soll.

**10 - Hier die Einstellungen dazu**
![10-modul buchungsuberblick](https://user-images.githubusercontent.com/29429097/29013930-78ff87be-7b46-11e7-9e19-93564934e53a.JPG)

Aus meiner Sicht sind die Daten in der Datenbank in Ordnung und werden mit Contao-Standardmitteln auch sauber wieder angezeigt. Warum das aber im Modul TableReservation selbst nicht funktioniert ist unerklärlich. Ich bin da auch mit meinem Latein am Ende.

**Comment by dennis-sagasser** [comment]
Leider kann ich nicht weiterhelfen ohne Debugging-Möglichkeit.

Gibt es eine Möglichkeit es auf einem anderen Server zu installieren? Es ist auch möglich, die Erweiterung manuell hier runterzuladen und in den Ordner system/modules zu packen.

**Comment by ghost** [comment]
Nach tagelanger Fehlersuche, Studium von php-Befehlen und wilder Suche im Quellcode habe ich jetzt die vermeintlich fehlerverursachende Stelle ausmachen (und korrigieren) können:

Siehe hier:
"..\system\modules\table_reservation\modules\ModuleTableReservation.php"

![grafik](https://user-images.githubusercontent.com/29429097/30150175-b34654e4-93aa-11e7-90fd-73c73dc14087.png)

Mit der Änderung von $strArrival auf $strArrivalTime funktioniert jetzt die Darstellung der korrekten Zeit im Frontend...

![grafik](https://user-images.githubusercontent.com/29429097/30150322-303c0a2a-93ab-11e7-8d21-07a6f2f8ab74.png)

... und auch in der verschickten Mail.

![grafik](https://user-images.githubusercontent.com/29429097/30150397-86e320b6-93ab-11e7-9f9b-b6dd675ff540.png)


Alles gut jetzt mit nur 4 zusätzlichen Buchstaben. Bin jetzt auf deinen Kommentar aus Entwicklersicht gespannt.

**Comment by jscholtysik** [comment]
Ich hatte bisher immer die Version direkt von Github gezogen, dort trat der Fehler nie auf...

Viele Grüße.

--------------------------------------
Joachim Scholtysik

**Comment by ghost** [comment]
Hallo Joachim,

die Herkunft der Version scheint nicht die Ursache zu sein. Bei der GitHub-Version hier sehe ich den gleichen (Fehler? im) Quelltext wie bei meiner Version aus dem ER. Warum das Problem "nur" in meiner Version auftritt und nicht generell, weiss ich auch nicht. Vielleicht hilft Dennis diese Info aber bei der Analyse / Fehlersuche.

Frank

**Comment by dennis-sagasser** [comment]
Hi,

danke für deine Bemühungen. Ich will das verstehen. Was hast du im Modul bei Datums- und Zeitformat eingetragen? Wenn dort nichts eingetragen ist, was steht in dem Feld in den Einstellungen von Contao?

**Comment by ghost** [comment]
![grafik](https://user-images.githubusercontent.com/29429097/30207496-028e30fe-9490-11e7-9d15-290c41e746f9.png)

![grafik](https://user-images.githubusercontent.com/29429097/30207534-2903eff8-9490-11e7-9033-00a07a621ef1.png)

Hier die Screenshots dazu. Sag ruhig Bescheid, wenn Du noch weitere Info's brauchst. Mich interessiert das auch, warum das "nur" bei mir nicht funktioniert. Übrigens ist meine Lösung auch noch nicht der Weisheit letzter Schluss, weil da das Datum fehlt und nur die Uhrzeit ausgegeben wird. Ich hab die Zeile noch auf: sprintf('%s %s - %s', $strArrivalDate, $strArrivalTime, $strDepartureTime); korrigiert, damit kommt das Datum dann mit raus. Lediglich ein ordentliches Datumsformat hab ich mit meinen rudimentären php-Kenntnissen (noch) nicht hingekriegt. ;-)

Schönes Wochenende!

**Comment by dennis-sagasser** [comment]
Hallo Frank,

trage doch bitte mal das Datums- und Zeitformat der globalen Einstellungen in das gleichnamige Feld der Modulkonfiguration ein und sage mir, ob es dann klappt.

Grüße
Dennis

**Comment by ghost** [comment]
Hi Dennis,

große Verwunderung und Überraschung - mit den Formateinstellungen im Massagemodul selbst funktioniert das super. Sieht so aus, wie es soll (sogar mit den zurückgedrehten Änderungen im php-Skript). Bin sehr erstaunt.

Dann scheint es wohl irgendwie Probleme zu geben, das globale Format durchzureichen. Zumindest gibt's jetzt eine Lösung auf "regulärem" Weg. Bin sehr erleichtert.

Viele Grüße
Frank

**Comment by dennis-sagasser** [comment]
Hi Frank,

Ich konnte den Fehler lokalisieren. Durch das Einfügen des JavaScript Widgets für die Datumsauswahl sind einige Zeilen Code weggefallen. So auch der Fallback auf das globale Datumsformat, wenn das Feld im Modul leer ist. Der Fehler tritt nur bei Leuten auf, bei denen das Feld leer ist. Ich werde das sobald wie möglich korrigieren und danke dir für deine Hilfe bei der Fehlersuche.

Gruß
Dennis
