### ISSUE TITLE
Buchung nicht möglich, wenn Tischkategorie nicht veröffentlicht

### ISSUE THREAD

**Issue by ghost** [dennis-sagasser/contao-table-reservation#30]
Wird in den Einstellungen, das Häkchen bei "Tischkategorie veröffentlichen" entfernt
![tischkategorie](https://user-images.githubusercontent.com/29429097/27167265-3fbabee4-51a0-11e7-974c-d1eee2e78194.JPG)

so ist es nicht möglich, einen Termin zu buchen, da die Schaltflächen für "Verfügbarkeit prüfen" und "Jetzt reservieren" nicht mehr angezeigt werden.
![anmeldung](https://user-images.githubusercontent.com/29429097/27167309-762db5bc-51a0-11e7-94a4-e7dee5395ca4.JPG)

**Comment by dennis-sagasser** [comment]
Das eine Buchnung unter den Voraussetzungen nicht möglich ist, soll schon so sein. Das könnte natürlich für den Buchenden eleganter aussehen.
