### ISSUE TITLE
Tischkategorie ausblenden, wenn nur eine vorhanden?

### ISSUE THREAD

**Issue by tblumrich** [dennis-sagasser/contao-table-reservation#32]
Hallo!

Vielen Dank für das prima Modul!
Besteht eine einfache Möglichkeit, das man bei nur einer eingerichteten Kategorie die Checkbox im Frontend ausblenden kann oder sie zumindest schon angehakt ist? 

Vielen Dank.

**Comment by ghost** [comment]
Oh ja, das fände ich auch gut - würde ein paar Extraklicks ersparen.
