### ISSUE TITLE
Date/Time Label and Input field are separated after error message

### ISSUE THREAD

**Issue by jscholtysik** [dennis-sagasser/contao-table-reservation#6]
When I insert a date and time that is in the past, an error message appears:

"Der nächstmögliche Reservierungszeitpunkt ist nach..."

but the date/time label and the input field are separated from each other, because the error message will be displayed between label and inout field...

**Comment by dennis-sagasser** [comment]
That is the way it should be. Please see https://github.com/contao/core/issues/2629.
