### ISSUE TITLE
FR: Replace button "Verfügbarkeit prüfen" with "Jetzt reservieren", when reservation is possible

### ISSUE THREAD

**Issue by jscholtysik** [dennis-sagasser/contao-table-reservation#7]
- Check a date for a reservation
- If the reservation is possible, the link "jetzt reservieren >>" appears
- Change the link also to a button and replace the button "Verfügbarkeit prüfen" with this new button

**Comment by dennis-sagasser** [comment]
What should happen with the form to check the availability then? In my opinion it is an advantage to be able to change date and time in one step. So there is no need to provide a back/cancel button. Change the link to a button needs only a little CSS adaption. What do you mean?

**Comment by jscholtysik** [comment]
When I search for a possible reservation and found one, there is normally no more need to further display the button "Verfügbarkeit prüfen". Or the link "Jetzt reservieren" and the button "Verfügbarkeit prüfen" are then positioned near each other at the end of the form.

Concerning the link "Jetzt reservieren": We should provide a basic CSS so that the link looks also like a button, not a link. When required I can provide such a basic CSS file to you.
