### ISSUE TITLE
FR: Time limit per day (opening hours)

### ISSUE THREAD

**Issue by jscholtysik** [dennis-sagasser/contao-table-reservation#8]
Perhaps add a possibility to insert and display the opening hours, because ist does not make a sense when the restaurant is open only for example between 17.30 and 23.30 o'clock and a reservation comes in for 11.30 o'clock. So a limitation for the reservation hours would be very useful...

**Comment by jscholtysik** [comment]
Please delete also here the seconds in the fields "Von" and "Bis". Thank you!

**Comment by dennis-sagasser** [comment]
Did you specify the wanted time format above opening hours?

**Comment by jscholtysik** [comment]
Sorry, I have overseen it... :-(
