### ISSUE TITLE
FR: Option in settings to select between a point of time or a timeslot

### ISSUE THREAD

**Issue by jscholtysik** [dennis-sagasser/contao-table-reservation#9]
Let the restaurant owner decide in the settings whether he offers the possibility to adjust date and time settings or timeslots concerning his restaurant plan. 

Example:

Date and time: 13.07.2017 19:30:00
or
Date and timeslot: 13.07.2017 19:00:00 - 20:30:00

**Comment by jscholtysik** [comment]
Small typo in the tooltip at "Zeitfenster aktivieren": 

"Öffunungszeiten" instead "Öffnungszeiten"...

**Comment by jscholtysik** [comment]
And please provide also a label for the ID "ctrl_timeslots", when "Zeitfenster aktivieren" is selected in the backend.

**Comment by jscholtysik** [comment]
Danke!

**Comment by jscholtysik** [comment]
I think, we have still an error in thinking about timeslots and seats.

For example:
 
A restaurant has open from 18:00 to 24:00 o'clock, has 20 seats in the restaurant and four timeslots:

Example:
18:00-19:30
19:30-21:00
21:00-22:30
22:30-24:00

So the restaurant has then not 20 seats, but 80 seats that clients can book per day, 20 seats per timeslot. The calendar in the backend can actually only show the quantity of all seats together, but not 20 seats per defined timeslot, so the calendar is actually not able to spread the maximum of 80 seats into these four timeslots and the waiter must eventually juggling with paper to find a solution that fits for all seats. It means then that actually there can be booked more than 20 seats per timeslot, because the calendar does not know that it can only accept a maximum of 20 seats per timeslot.

Do you also see the problem?

**Comment by dennis-sagasser** [comment]
Yes I can follow you but do you think the waiter wants to set timeslots for every day of the year the restaurant is opened? In my eyes that is the only way to solve the problem or can you make a better suggestion?

**Comment by jscholtysik** [comment]
The waiter only has to set the timeslots once a year, at the beginning of the year. Normally the timeslots don't change. Or the timeslots once defined are automatically transferred into the next year, but can then also be manually edited.

So the orders would be:

If the restaurant has no timeslots, but normal open hours:
- The actual calendar is right
- The restaurant defines only the open hours in the module and the number of its seats in the calendar
- The extension manages the seats per open hours per day and must check whether an order can be set in the open hours

If the restaurant has timeslots:
- A new calendar is needed where the timeslots can be used depending on the number of timeslots
- The restaurant defines once the timeslots (number of timeslots and duration) in the module and the number of seats per timeslot in the calendar
- The extension manages the seats per timeslot per day and must check whether an order can be set in the corresponding time slot

**Comment by dennis-sagasser** [comment]
> The waiter only has to set the timeslots once a year, at the beginning of the year. Normally the timeslots don't change. Or the timeslots once defined are automatically transferred into the next year, but can then also be manually edited.

The extension is based on an annual calendar and in a calendar every day is different. So transfer time slots to the next year would make no sense. Think about only public holidays and vacation time. So the waiter would have to set time slots for every day but I doubt that a restaurant in reality has additional times within opening hours, within a daytime and then also every day different. 

> So the orders would be:

> If the restaurant has no timeslots, but normal open hours:
> 
>     The actual calendar is right
>     The restaurant defines only the open hours in the module and the number of its seats in the calendar
>     The extension manages the seats per open hours per day and must check whether an order can be set in the open hours

Yes, the base of the extension is the calendar where you can enter the available seats for three daytimes. When the user enters a date and time or time slot within a daytime the system checks if there are available seats in the calendar.

>  If the restaurant has timeslots:

>     A new calendar is needed where the timeslots can be used depending on the number of timeslots
>     The restaurant defines once the timeslots (number of timeslots and duration) in the module and the number of seats per timeslot in the calendar
>     The extension manages the seats per timeslot per day and must check whether an order can be set in the corresponding time slot

I know what you want to achieve but this way would require a complete restructuring of the extension in back- and frontend. Furthermore I do not think it is a good way to make settings to one issue in two different places (calendar and module settings).

**Comment by jscholtysik** [comment]
No, an option is needed where the restaurant can set all timeslots at once.

Like in editing the time spans in the categories:

![bildschirmfoto 2017-04-05 um 12 50 47](https://cloud.githubusercontent.com/assets/1425566/24702363/bdfaa460-19fe-11e7-9d88-b9357b2e8674.png)

So the restaurant can select the time span checkbox, selects then the whole year and inserts then the timeslots for the whole year.  Exceptions like holidays can the edited manually. Nothing different than the actual solution imho.

A restaurant can have open hours where the client can book at a certain time and stay as long as he want to stay (the actual and complete possibility) or timeslots at certain open hours, where the restaurant can define the maximum of time the client can stay (actually partly possible). Not both variants!! Timeslots cause that a seat is available multiple times a day, not only once.

I know both variants here in restaurants in Munich... no restaurant has both variants, but one of them.

**Comment by jscholtysik** [comment]
I think it could be the same systematics as with the categories:

Every category has its own calendar, so if the restaurant has normal open hours and two different categories, the categories can hold its own number of seats and also can control them.
1 category = normal open hours = 1 calendar
2 categories = 2 calendars
etc.

With the timeslots:
Every category can have it own calendar, so if the restaurant has for example four timeslots, every timeslot should have its own calendar and the restaurant is able to control the seats in every timeslot, so no manual work has to be done... ;-)

1 timeslot = normal open hours = 1 calendar
2 timeslots = 2 calendars
3 timeslots = 3 calendars
etc.

The same is possible on commercial planners, for example www.freizeitplan.net.

**Comment by dennis-sagasser** [comment]
Ok...so we need an additional variant of the calendar to store the number of available seats for determinated time slots for every day. 

Therefore we need a place to define the time slots. To put it into the category would not be a good idea because then we mix up normal and time slot categories which could e.g. not be booked together.

The challenge is to make it possible to define first time slots that then appear in the annual calendar. Technically we need to dynamically create columns for the occupancy table. My goal is to create another backend menu item for the time slots that manipulates the occupancy table according to the time slot fields and when the calendar is loaded the dca field will be created. What do you mean?

**Comment by jscholtysik** [comment]
Sounds good! I would also not mix up categories and time slots in one mask and would create a new menu item to set the time slots to differ the two methods. But the system in the categories is already good solved: Creating a new category creates a new calendar, so creating a new time slot would create also a new calendar in the new menu item for the time slots. so categories and time slots are clearly separated.

**Comment by jscholtysik** [comment]
Some problems with the new time slots menu item:

1. The help text under "From" and "To" does not fit:

![time slots](https://cloud.githubusercontent.com/assets/1425566/25268308/8953f69a-2678-11e7-9726-9c046a5025e3.jpg)

2. Then I created a new time slot. The time slot name can not have spaces, can this be changed?

![time slots name](https://cloud.githubusercontent.com/assets/1425566/25268437/fe921130-2678-11e7-9ff8-5eac210f0237.jpg)

3. Then I have created a time slot, saw the new time slot in the calendar and deleted the time slot again. It is ok. When I then go into the table categories, I see the following:

![time slots table categories](https://cloud.githubusercontent.com/assets/1425566/25268598/9cdad408-2679-11e7-9fd2-54427a59e89f.jpg)

But editing of the table categories is no more possible, I get an error message in system/logs:

> [21-Apr-2017 09:50:20 Europe/Berlin] PHP Fatal error: Uncaught exception 'Exception' with message 'Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM    tl_table_occupancy 
                WHERE   date='2017-01-01' 
         ' at line 2 (SELECT  
                FROM    tl_table_occupancy 
                WHERE   date='2017-01-01' 
                AND     pid=4)' thrown in /www/htdocs/w014a7e9/system/modules/core/library/Contao/Database/Statement.php on line 295
#0 /www/htdocs/w014a7e9/system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 /www/htdocs/w014a7e9/system/modules/table_reservation/classes/tl_table_occupancy.php(164): Contao\Database\Statement->execute('2017-01-01', 4)
#2 /www/htdocs/w014a7e9/system/modules/table_reservation/classes/tl_table_occupancy.php(121): Contao\tl_table_occupancy->datesMonth(1, 2017, 4)
#3 /www/htdocs/w014a7e9/system/modules/core/classes/DataContainer.php(224): Contao\tl_table_occupancy->generateCalendarWidget(Object(Contao\DC_Table), '')
#4 /www/htdocs/w014a7e9/system/modules/core/drivers/DC_Table.php(1943): Contao\DataContainer->row('{date_legend},s...')
#5 /www/htdocs/w014a7e9/system/modules/core/classes/Backend.php(650): Contao\DC_Table->edit()
#6 /www/htdocs/w014a7e9/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('table_categorie...')
#7 /www/htdocs/w014a7e9/contao/main.php(20): Contao\BackendMain->run()
#8 {main}
